import React from "react";
import Head from "next/head";
import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "About Eric",
  description: "Generated by create next app",
};

const About = () => {
  return (
    <>
      <main className="flex w-full flex-col items-center justify-center">
        <Layout className="pt-16">
          <AnimatedText text="Another slogan or moto" className="" />
          <div className="grid w-full grid-cols-8 gap-16">
            <div className="col-span-3 flex flex-col items-start justify-start">
              <h2 className="mb-4 text-lg font-bold uppercase text-dark/75">
                About Me
              </h2>
              <p className="font-medium">
                Intro paragraph here. A little about myself
              </p>
              <p className="font-medium my-4">Beliefs or fun stuff I do</p>
              <p className="font-medium">CTA stuff here</p>
            </div>
          </div>
          <div>
            {/* TODO: add a profile pic */}
            {/* <Image
              src={}
              alt="Eric CHen"
              className="w-full h-auto rounded-2xl"
            /> */}
          </div>
        </Layout>
      </main>
    </>
  );
};

export default About;
